global using System.Linq;
global using TouMegaChujoweExtension.Assets;
global using TouMegaChujoweExtension.Buttons.Classic.Crewmate;
global using TouMegaChujoweExtension.Buttons.Classic.Impostor;
global using TouMegaChujoweExtension.Buttons.Classic.Neutral;
global using TouMegaChujoweExtension.Buttons.Modifiers;
global using TouMegaChujoweExtension.Events.Crewmate;
global using TouMegaChujoweExtension.Events.Impostor;
global using TouMegaChujoweExtension.Events.Modifiers;
global using TouMegaChujoweExtension.Events.Neutral;
global using TouMegaChujoweExtension.Events;
global using TouMegaChujoweExtension.GameOver;
global using TouMegaChujoweExtension.Modifiers.Crewmate;
global using TouMegaChujoweExtension.Modifiers.Impostor;
global using TouMegaChujoweExtension.Modifiers.Neutral;
global using TouMegaChujoweExtension.Modifiers.Game;
global using TouMegaChujoweExtension.Modules;
global using TouMegaChujoweExtension.Networking;
global using TouMegaChujoweExtension.Options;
global using TouMegaChujoweExtension.Options.Modifiers.Impostor;
global using TouMegaChujoweExtension.Options.Modifiers.Neutral;
global using TouMegaChujoweExtension.Options.Modifiers.Universal;
global using TouMegaChujoweExtension.Options.Roles.Crewmate;
global using TouMegaChujoweExtension.Options.Roles.Impostor;
global using TouMegaChujoweExtension.Options.Roles.Neutral;
global using TouMegaChujoweExtension.Patches.BugFixes;
global using TouMegaChujoweExtension.Patches.Roles;
global using TouMegaChujoweExtension.Patches.Draft;
global using TouMegaChujoweExtension.Patches.Roles.Assasin;
global using TouMegaChujoweExtension.Patches.Roles.Bodyguard;
global using TouMegaChujoweExtension.Patches.Roles.BountyHunter;
global using TouMegaChujoweExtension.Patches.Roles.Charlatan;
global using TouMegaChujoweExtension.Patches.Roles.Clueless;
global using TouMegaChujoweExtension.Patches.Roles.Doppelganger;
global using TouMegaChujoweExtension.Patches.Roles.Drunk;
global using TouMegaChujoweExtension.Patches.Roles.Egotist;
global using TouMegaChujoweExtension.Patches.Roles.Evoker;
global using TouMegaChujoweExtension.Patches.Roles.Forestaller;
global using TouMegaChujoweExtension.Patches.Roles.Foreteller;
global using TouMegaChujoweExtension.Patches.Roles.Hacker;
global using TouMegaChujoweExtension.Patches.Roles.Injector;
global using TouMegaChujoweExtension.Patches.Roles.Lawyer;
global using TouMegaChujoweExtension.Patches.Roles.Lovers;
global using TouMegaChujoweExtension.Patches.Roles.MirageDecoy;
global using TouMegaChujoweExtension.Patches.Roles.Pelican;
global using TouMegaChujoweExtension.Patches.Roles.Pirate;
global using TouMegaChujoweExtension.Patches.Roles.Poisoner;
global using TouMegaChujoweExtension.Patches.Roles.Pope;
global using TouMegaChujoweExtension.Patches.Roles.President;
global using TouMegaChujoweExtension.Patches.Roles.Publicity;
global using TouMegaChujoweExtension.Patches.Roles.RcXd;
global using TouMegaChujoweExtension.Patches.Roles.SerialKiller;
global using TouMegaChujoweExtension.Patches.Roles.Shroud;
global using TouMegaChujoweExtension.Patches.Roles.Sonar;
global using TouMegaChujoweExtension.Patches.Roles.Spiteful;
global using TouMegaChujoweExtension.Patches.Roles.TimeLord;
global using TouMegaChujoweExtension.Patches.Roles.Trapper;
global using TouMegaChujoweExtension.Patches.Roles.Venomous;

global using TouMegaChujoweExtension.Patches.Roles.Witch;
global using TouMegaChujoweExtension.Patches.Roles.Wraith;
global using TouMegaChujoweExtension.Patches.UI;
global using TouMegaChujoweExtension.Patches.Wiki;
global using TouMegaChujoweExtension.Patches.WinConditions;
global using TouMegaChujoweExtension.Roles.Classic.Crewmate;
global using TouMegaChujoweExtension.Roles.Classic.Impostor;
global using TouMegaChujoweExtension.Roles.Classic.Neutral;
global using TouMegaChujoweExtension.Utilities;
global using HackerRole = TouMegaChujoweExtension.Roles.Classic.Impostor.HackerRole;
global using TrapperRole = TouMegaChujoweExtension.Roles.Classic.Crewmate.TrapperRole;
global using VultureRole = TouMegaChujoweExtension.Roles.Classic.Neutral.VultureRole;
global using PelicanRole = TouMegaChujoweExtension.Roles.Classic.Neutral.PelicanRole;
global using LawyerRole = TouMegaChujoweExtension.Roles.Classic.Neutral.LawyerRole;
global using BountyHunterRole = TouMegaChujoweExtension.Roles.Classic.Neutral.BountyHunterRole;
global using SerialKillerRole = TouMegaChujoweExtension.Roles.Classic.Neutral.SerialKillerRole;
global using DoppelgangerRole = TouMegaChujoweExtension.Roles.Classic.Neutral.DoppelgangerRole;
global using ShroudRole = TouMegaChujoweExtension.Roles.Classic.Neutral.ShroudRole;
global using PoisonerRole = TouMegaChujoweExtension.Roles.Classic.Impostor.PoisonerRole;
global using WitchRole = TouMegaChujoweExtension.Roles.Classic.Impostor.WitchRole;
global using WitchOptions = TouMegaChujoweExtension.Options.Roles.Impostor.WitchOptions;
global using WitchEvents = TouMegaChujoweExtension.Events.Impostor.WitchEvents;
global using WitchSpellboundModifier = TouMegaChujoweExtension.Modifiers.Impostor.WitchSpellboundModifier;
global using static Reactor.Utilities.Logger<TouMegaChujoweExtension.TouMegaChujoweExtensionPlugin>;
global using TownOfUs.Extensions;
global using TownOfUs.Networking;
global using MiraAPI.Networking;
global using MiraAPI.LocalSettings;
global using MiraAPI.GameOptions;
global using TownOfUs.Assets;