<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <DebugType>embedded</DebugType>
        <Nullable>enable</Nullable>
        <RootNamespace>TouMegaChujoweExtension</RootNamespace>
        <Description>Fork of Rewalo's Town Of Us Mira Roles Extension, adds draft mode and a bunch of new roles and modifiers.</Description>
        <Authors>Heker, marzecoo, kajojajo</Authors>
        <Version>$(VersionPrefix)</Version>
        <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
        <FileVersion>$(VersionPrefix)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources/**/*.*" />
    </ItemGroup>

    <ItemGroup Condition="Exists('Resources/Audio/toumega-audio-win.bundle') Or Exists('Resources/Audio/toumega-audio-android.bundle')">
        <EmbeddedResource Remove="Resources/Audio/**/*.mp3" />
        <EmbeddedResource Remove="Resources/Audio/**/*.ogg" />
        <EmbeddedResource Remove="Resources/Audio/**/*.wav" />
    </ItemGroup>

    <ItemGroup Condition="Exists('Resources/Sprites/toumega-sprites-win.bundle') Or Exists('Resources/Sprites/toumega-sprites-android.bundle')">
        <EmbeddedResource Remove="Resources/**/*.png" />
        <EmbeddedResource Include="Resources/Anims/**/*.png" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />

    <Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
    </Target>
</Project>
