name: CI

on: ["workflow_dispatch", "push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run the Cake script
        uses: cake-build/cake-action@v3
        with:
          verbosity: Diagnostic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: TouMegaChujoweExtension.dll
          path: TouMegaChujoweExtension/bin/Release/net6.0/TouMegaChujoweExtension.dll

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: TouMegaChujoweExtension/bin/Release/net6.0/TouMegaChujoweExtension.dll